config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :contacts

resources :prefectures

resources :hotels do
  resources :reviews
  resources :reservations
end

root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	mount_uploader :picture, PictureUploader
	belongs_to :prefecture
	has_many :reviews
	has_many :reservations
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :hotels
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :hotel
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

   def new
      @contact = Contact.new
   end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contact_path(@contact)
    end
  end

  def show
     @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	def index
      @hotels = Hotel.all
      @q = Hotel.ransack(params[:q])
      @hotels = @q.result(distinct: true)
    end

    def show
       @hotel = Hotel.find(params[:id])
    end

    def hotel_params
       params.require(:hotel).permit(:name, :picture, :descripition, :number_of_rooms)
    end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
	def index
      @prefectures = Prefecture.all
    end

    def show
       @prefecture = Prefecture.find(params[:id])
       @hotels = @prefecture.hotels.all
    end

    def prefecture_params
       params.require(:prefecture).permit(:name, :picture,:descripition)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	 def new
       @hotel = Hotel.find(params[:hotel_id])
       @reservation = @hotel.reservations.build
     end

    def create
      @hotel = Hotel.find(params[:hotel_id])
      @reservation = Reservation.new(reservation_params)

       if @reservation.save
           redirect_to reservation_path(@reservation)
       end
    end

  def show
    @hotel = Hotel.find(params[:hotel_id])
     @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:name, :email, :checkin, :checkout, :transport, :number, :hotel_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
	  @hotel = Hotel.find(params[:hotel_id])
      @reviews = @hotel.reviews
    end

    def show
       @hotel = Hotel.find(params[:hotel_id])
       @review = Review.find(params[:id])
    end

	def new
      @hotel = Hotel.find(params[:hotel_id])
      @review = Review.new
    end

    def create
     @hotel = Hotel.find(params[:hotel_id])
     @review = Review.new(review_params)
     if @review.save
     	redirect_to hotel_reviews_path(@hotel)
     end
    end


    def review_params
       params.require(:review).permit(:name, :sex, :age, :rate, :body, :time, :hotel_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/contacts/new.html.erb
<h1>お問い合わせ内容</h1>

<%= form_with(model: @contact, local: true) do |form| %>
<!-- name -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>
<!-- description -->
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<h1>お問い合わせ内容</h1>
<p><%= @contact.name %></p>
<p><%= @contact.email %></p>
<p><%= @contact.content %></p>
<%= link_to 'Back', new_contact_path %> |


app/views/hotels/index.html.erb
<h1 class="ml-4"><span>ホテル一覧</span></h1>

<div class="d-flex flex-row-reverse bd-highlight">
<form class="hotel_search" id="hotel_search" action="/hotels" accept-charset="UTF-8" method="get">
  <input name="utf8" type="hidden" value="✓">

<div class="p-2 bd-highlight">
  <input class="search" type="search" name="q[name_cont]" id="q_name_cont" placeholder="ホテル名を入力">
  <input type="submit" name="commit" value="検索" data-disable-with="Search" class="btn btn-success"> |
  <input class="search" type="search" name="q[prefecture_name_cont]" id="q_prefecture_name_cont" placeholder="都道府県名を入力">
  <input type="submit" name="commit" value="検索" data-disable-with="Search" class="btn btn-success">
</div>

</form>
</div>

 <div class="container-fluid">
   <div class="row">
     <% @hotels.each do |hotel| %>
      <div class="col-md-3">
         <div class="card" style="width: 18rem;">
          <div class="card-header">
            <p class="text-center h4"><em><%= hotel.name %></em></p>
          </div>
           <div class="card-body">
             <p class="card-text">
                      <p>
                      <%= image_tag(hotel.picture_url, width: 250) if hotel.picture.present? %>
                      </p>

                      <p>詳細:   <%= hotel.description %></p>
                      <p>部屋数:   <%= hotel.number_of_rooms %></p>
                  </p>
              </div>
              <div class="d-flex justify-content-around">
                <div class="card-footer">
                  <%= link_to '詳細', hotel_path(hotel) %> :
                  <%= link_to ' レビューを見る', hotel_reviews_path(hotel) %> 
                </div>
              </div>
          </div>
      </div>
      <% end %>
   </div>
 </div>
 

app/views/hotels/show.html.erb

<p>
  <strong>ホテル名:</strong>
  <%= @hotel.name %>
</p>

<p>
  	<img class="hotpic" width="300" src="/uploads/hotel/picture/1/1.png">
</p>

<p>
  <strong>詳細:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>所在地:</strong>
  <%= @hotel.prefecture.name %>
</p>

<p>
  <strong>部屋数:</strong>
  <%= @hotel.number_of_rooms %>
</p>

<a class="btn btn-success" href="/hotels/1/reservations/new">予約する</a> |
<a class="btn btn-success" href="/hotels">戻る</a>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Hotel Project</title>
  </head>
  
  <body>

    <header>
    <div class="container">
     <nav class="navbar navbar-expand-sm navbar-light">
       <a class="navbar-brand font-italic" href="/" style="font-size: 30px"><u>Hotel Project</u></a>
       <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
       <span class="navbar-toggler-icon"></span>
       </button>

       <div id="menu" class="collapse navbar-collapse d-flex justify-content-end">
         <ul class="navbar-nav">
           <li class="nav-item"><a href="/" class="nav-link">トップページ</a></li>
           <li class="nav-item"><a href="/contacts/new" class="nav-link">お問い合わせ</a></li>
         </ul>
       </div>
      </nav>  
    </div>
    </header>

    <%= yield %>
    <h1></h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

  <footer class="mt-5">
    <p class="text-center text-muted display-5">~Hotel Project~</p>
  </footer>
</html>

app/views/prefectures/index.html.erb
<p>都道府県一覧</p>
<% @prefectures.each do |prefecture| %>
  <p><%= prefecture.name %></p>

  <p><%= prefecture.description %></p>
  <%= link_to '詳細', prefecture %> 
<% end %>

app/views/prefectures/show.html.erb
<p>
  <strong>県名:</strong>
  <%= @prefecture.name %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @prefecture.description %>
</p>

<% @hotels.each do |hotel| %>
  <p><%= hotel.name %></p>
  <p>
  	<%= image_tag(hotel.picture_url, width: 300) if hotel.picture.present? %>
  </p>

  <p><%= hotel.description %></p>
  <p><%= hotel.number_of_rooms %></p>
<% end %>

<%= link_to 'Back', prefectures_path %> 

app/views/reservations/new.html.erb
<h1>ホテルの予約</h1>

<p>
  <strong>名前</strong>
  <div class="field">
	  <input id="reservation_name" type="text" size="70" name="reservation[name]" placeholder="代表者様のお名前を入力してください">
  </div>
</p>

<p>
  <strong>メールアドレス</strong>
  <div class="field">
	<input id="reservation_email" size="70" type="text" name="reservation[email]" placeholder="メールアドレスを入力してください">
  </div>
</p>

<p>
 <div class="field">
  <%= form_with(model: [@hotel, @reservation], local: true) do |form| %>
    <%= form.label :チェックイン時間 %>
    <%= form.datetime_select :checkin, use_month_numbers: true %>
  <% end %>
 </div>
</p>

<p>
 <div class="field">
  <%= form_with(model: [@hotel, @reservation], local: true) do |form| %>
    <%= form.label :チェックアウト時間 %>
    <%= form.datetime_select :checkout, use_month_numbers: true %>
  <% end %>
 </div>
</p>

<p>
 <div class="btn-group">
  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    駐車場の利用
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">あり</a>
    <a class="dropdown-item" href="#">なし</a>
  </div>
</div>
</p>

<p>
 <div class="field">
	<input id="reservation_number" type="text" name="reservation[number]" placeholder="人数">
 </div>
</p>

<div class="actions">
    <input type="submit" name="commit" value="予約送信" data-disable-with="予約送信" class="btn btn-info">
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: [@hotel, review], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <%= form.text_field :hotel_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<p>レビュー一覧</p>
<% @reviews.each do |review| %>
  <p>
    <%= review.name %>
    <%= review.body %>
  </p>
  <% end %>

app/views/reviews/new.html.erb
<h1>レビュー作成</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', hotel_reviews_path %>